### PR TITLE
Update backend_test.py

### PR DESCRIPTION
**Pull request by cqc-melf**
# Description

Please summarise the changes.

# Related issues

Please mention any github issues addressed by this PR.

# Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented hard-to-understand parts of my code.
- [ ] I have made corresponding changes to the public API documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have updated the changelog with any user-facing changes.

### CODE REVIEW

**Review by cqc-alec — DISMISSED** [review]

**Comment by cqc-melf** [comment]
Updated the wrong testcase

**Comment by cqc-melf** [comment]
I am not sure what is happening, I see both results from time to time. I would suggest this as a temp fix, but we should follow on and check what is really going on remotely on QA...

**Review by cqc-alec — APPROVED** [review]
Should we make a new issue to track this?

**Comment by cqc-melf** [comment]
Here is a the issue: https://github.com/CQCL/pytket-quantinuum/issues/417

**Comment by cqc-melf** [comment]
@cqc-alec I would merge this without the calender check working?

**Comment by cqc-alec** [comment]
> @cqc-alec I would merge this without the calender check working?

Yes, that's an unrelated issue.

**Review by cqc-alec — APPROVED** [review]

**Pull request merged**
