### PR TITLE
update pytket-qir and pytket version

### PR DESCRIPTION
**Pull request by cqc-melf**

### CODE REVIEW

**Review by cqc-alec — CHANGES_REQUESTED** [review]
Need to upgrade the version here:

https://github.com/CQCL/pytket-quantinuum/blob/98f900c922468c390b61679a3f626878e796e272/.github/workflows/build-test#L66

**Comment by cqc-alec** [comment]
Are all the test failures QIR-related? Are they all versions of #236 or are there other issues here?

If there are some QIR tests that we expect to fail currently can we mark them as expected failures in pytest?

**Comment by cqc-melf** [comment]
> Are all the test failures QIR-related? Are they all versions of #236 or are there other issues here?
> 
> If there are some QIR tests that we expect to fail currently can we mark them as expected failures in pytest?

I had seen this issues in the past and I thought that is was already solved. I am not sure why it is showing up again, looks like there has been some changes in the backend. I will bring this up later today.

I think it is the best solution to disable the tests for now and do the release to get the wasm fix out.

**Comment by cqc-alec** [comment]
There seems to be one test failure (`test_cancel`) which I don't understand. Maybe worth rerunning in case it is an ephemeral thing?

**Comment by cqc-melf** [comment]
> There seems to be one test failure (`test_cancel`) which I don't understand. Maybe worth rerunning in case it is an ephemeral thing?

Looks like it is gone after a rerun, I have not seen that in any local runs

**Review by cqc-alec — APPROVED** [review]

**Pull request merged**
