### PR TITLE
Remove references to device/system family.

### LINKED ISSUE #136: remove device families from documentation

### PR DESCRIPTION
**Pull request by cqc-alec**
This is no longer a thing that devices report.

Fixes #136 .

### CODE REVIEW

**Review by cqc-melf — COMMENTED** [review]
I think the documentation needs to be updated as well?

See https://cqcl.github.io/pytket-quantinuum/api/index.html#devices 
`* ``H1``: Submit to Quantinuum ``H1`` machines: job is run on ``H1-1`` or ``H1-2`` based on the soonest available device.` 

https://github.com/CQCL/pytket-quantinuum/blob/feature/nofamily/docs/intro.txt

**Comment by cqc-alec** [comment]
> I think the documentation needs to be updated as well?
> 
> See https://cqcl.github.io/pytket-quantinuum/api/index.html#devices `` * ``H1``: Submit to Quantinuum ``H1`` machines: job is run on ``H1-1`` or ``H1-2`` based on the soonest available device. ``

Thanks, done.

**Comment by cqc-melf** [comment]
And one more: https://github.com/CQCL/pytket-quantinuum/blob/feature/nofamily/pytket/extensions/quantinuum/backends/quantinuum.py#LL196C9-L196C54

**Comment by cqc-alec** [comment]
> And one more: https://github.com/CQCL/pytket-quantinuum/blob/feature/nofamily/pytket/extensions/quantinuum/backends/quantinuum.py#LL196C9-L196C54

Done.

**Review by cqc-melf — APPROVED** [review]

**Comment by cqc-melf** [comment]
Should we put out a release candidate or a new documentation to make sure this is out soon?

**Comment by cqc-alec** [comment]
> Should we put out a release candidate or a new documentation to make sure this is out soon?

I think we should do a release as soon as https://github.com/CQCL/pytket-quantinuum/pull/135 is merged, since people are asking for that.

**Pull request merged**
