### PR TITLE
use latest version and run testcases

### PR DESCRIPTION
**Pull request by cqc-melf**

### CODE REVIEW

**Comment by cqc-melf** [comment]
The other PR had some github issue, find early discussion on https://github.com/CQCL/pytket-quantinuum/pull/172

**Review by cqc-alec — APPROVED** [review]
Could you make a new issue for the division problem? Thanks!

**Comment by cqc-melf** [comment]
> Could you make a new issue for the division problem? Thanks!

Will do that.

**Comment by cqc-melf** [comment]
Can I merge this without the tests working? @cqc-alec

**Comment by cqc-alec** [comment]
> Can I merge this without the tests working? @cqc-alec

Ah I didn't see that the tests were failing, are these new issues? I don't mind merging though.

**Comment by cqc-melf** [comment]
@cqc-alec   They are all related to `ValueError: The qir optimised for pyqir 0.6 can only contain 
one classical register`

I think we can merge this and disable the pyqir 0.6 compatibility on the other PR to be runrun as soon as the api has been updated.

**Comment by cqc-alec** [comment]
> @cqc-alec They are all related to `ValueError: The qir optimised for pyqir 0.6 can only contain one classical register`
> 
> I think we can merge this and disable the pyqir 0.6 compatibility on the other PR to be runrun as soon as the api has been updated.

OK

**Pull request merged**
