### PR TITLE
Update docstrings in credential_storage.py

### LINKED ISSUE #483: Add doc strings to constructors in `credential_storage.py`

### PR DESCRIPTION
**Pull request by yao-cqc**
# Description

Please summarise the changes.

# Related issues

Resolves #483 

# Checklist

- [x] I have performed a self-review of my code.
- [ ] I have commented hard-to-understand parts of my code.
- [ ] I have made corresponding changes to the public API documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have updated the changelog with any user-facing changes.

### CODE REVIEW

**Review by cqc-alec — COMMENTED** [review]
I think what is missing here is an explanation of what the tokens are and how to obtain them (given a username and password) in the first place.

**Comment by yao-cqc** [comment]
> I think what is missing here is an explanation of what the tokens are and how to obtain them (given a username and password) in the first place.

I've added a brief explanation to the base class. Let me know if you think it should be more detailed.

**Comment by cqc-alec** [comment]
Thanks, I do think it needs more detail. Could you walk through the process of setting up the tokens? I still can't get it to work :-(

I've tried doing this:

```python
from pytket.extensions.quantinuum import QuantinuumAPI
from pytket.extensions.quantinuum.backends.credential_storage import (
    QuantinuumConfigCredentialStorage,
)

api = QuantinuumAPI()
id_token = api.login()
storage = QuantinuumConfigCredentialStorage()
storage.save_id_token(id_token)
```

followed by

```python
from pytket.extensions.quantinuum import QuantinuumBackend, QuantinuumAPI

api = QuantinuumAPI()
print(QuantinuumBackend.available_devices())
```

but I am still prompted for my password at the last stage. Obviously I'm doing something wrong here...

**Comment by yao-cqc** [comment]
> Thanks, I do think it needs more detail. Could you walk through the process of setting up the tokens? I still can't get it to work :-(
> 
> I've tried doing this:
> 
> ```python
> from pytket.extensions.quantinuum import QuantinuumAPI
> from pytket.extensions.quantinuum.backends.credential_storage import (
>     QuantinuumConfigCredentialStorage,
> )
> 
> api = QuantinuumAPI()
> id_token = api.login()
> storage = QuantinuumConfigCredentialStorage()
> storage.save_id_token(id_token)
> ```
> 
> followed by
> 
> ```python
> from pytket.extensions.quantinuum import QuantinuumBackend
> 
> print(QuantinuumBackend.available_devices())
> ```
> 
> but I am still prompted for my password at the last stage. Obviously I'm doing something wrong here...

I see...

`QuantinuumBackend` needs a `QuantinuumAPI` which needs a `CredentialStorage`.

`QuantinuumBackend` uses the `DEFAULT_API_HANDLER` by default, which has the `MemoryCredentialStorage`. Class methods of `QuantinuumBackend` also use the `DEFAULT_API_HANDLER` by default.

`QuantinuumAPI` will always save the username and tokens to its `CredentialStorage` after a successive `login`. Manually saving the tokens is usually not needed.

This should work:

```python
from pytket.extensions.quantinuum import QuantinuumAPI
from pytket.extensions.quantinuum.backends.credential_storage import (
    QuantinuumConfigCredentialStorage,
)
storage = QuantinuumConfigCredentialStorage()
api = QuantinuumAPI(token_store=storage)
api.login()

```
followed by

```python
from pytket.extensions.quantinuum import QuantinuumBackend
storage2 = QuantinuumConfigCredentialStorage()
api2 = QuantinuumAPI(token_store=storage2)
print(QuantinuumBackend.available_devices(api_handler=api2))

```

**Comment by cqc-alec** [comment]
> This should work:

Thanks for the explanation, clearly I was barking up the wrong tree. I don't think this is really explained anywhere in the docs -- maybe the section "Persistent Authentication Token Storage" in `docs/index.rst` could be expanded a little with the above workflow?

**Review by cqc-alec — APPROVED** [review]
Thanks!

**Pull request merged**
