### PR TITLE
Update python support to 3.10, 3.11 and 3.12

### PR DESCRIPTION
**Pull request by sjdilkes**
This PR drops python 3.9 support and adds python 3.12.

# Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented hard-to-understand parts of my code.
- [x] I have made corresponding changes to the public API documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have updated the changelog with any user-facing changes.

### CODE REVIEW

**Review by cqc-alec — COMMENTED** [review]
It looks like `llvmlite` does not yet have wheels available for Python 3.12. This is a test dependency. So we will have to disable the 3.12 tests on the CI until the next llvmlite release (just change 3.12 to 3.11 in the CI runs, and make a github issue to remind us to change it back when we can).

**Comment by cqc-alec** [comment]
Also, pytket-pecos doesn't currently have 3.12 support (waiting for a pytket-phir release to enable this). This means that installing with the "pecos" option won't work with 3.12. We should add a note about this in the "Local Emulators" section in `docs/intro.txt`.

**Comment by sjdilkes** [comment]
> It looks like `llvmlite` does not yet have wheels available for Python 3.12. This is a test dependency. So we will have to disable the 3.12 tests on the CI until the next llvmlite release (just change 3.12 to 3.11 in the CI runs, and make a github issue to remind us to change it back when we can).

issue added: https://github.com/CQCL/pytket-quantinuum/issues/327

**Comment by sjdilkes** [comment]
> Also, pytket-pecos doesn't currently have 3.12 support (waiting for a pytket-phir release to enable this). This means that installing with the "pecos" option won't work with 3.12. We should add a note about this in the "Local Emulators" section in `docs/intro.txt`.

note added

**Review by cqc-alec — APPROVED** [review]

**Pull request merged**
