### PR TITLE
Reenable QIR submission tests

### LINKED ISSUE #236: Test failure: `test_simulator[Language.QIR-H1-1E]`
Error message is:

```
"1000: Compile error: 1 Encountered Unexpected Instruction   %0 = call i1* @create_creg(i64 2)"
```

### PR DESCRIPTION
**Pull request by cqc-alec**
Closes #236 .

### CODE REVIEW

**Review by cqc-melf — COMMENTED** [review]
Do you want to do the update to pytket-qir 0.4.0 in this PR or do we want to do that seperatley?

**Comment by cqc-alec** [comment]
> Do you want to do the update to pytket-qir 0.4.0 in this PR or do we want to do that seperatley?

Maybe should do it here...

**Comment by cqc-alec** [comment]
> > Do you want to do the update to pytket-qir 0.4.0 in this PR or do we want to do that seperatley?
> 
> Maybe should do it here...

Done.

**Comment by cqc-melf** [comment]
Do we want to update the minimal version in here as well?

https://github.com/CQCL/pytket-quantinuum/blob/bugfix/enable-qir/pytket/extensions/quantinuum/backends/quantinuum.py#L830

(I would assume that we would be compatible with 0.3.0 , so maybe we don't need to do that.)

**Comment by cqc-alec** [comment]
> Do we want to update the minimal version in here as well?
> 
> https://github.com/CQCL/pytket-quantinuum/blob/bugfix/enable-qir/pytket/extensions/quantinuum/backends/quantinuum.py#L830

Done.

**Comment by cqc-melf** [comment]
My understanding is, that this tests are only run in the QA checks? So we cant be sure that this is really working?

**Comment by cqc-alec** [comment]
There were these failures:
```
============================================= short test summary info =============================================
FAILED integration/backend_test.py::test_simulator[Language.QIR-H1-1E] - assert 2 > 2
FAILED integration/backend_test.py::test_wasm_collatz[Language.QASM-H1-1E] - Failed: Timeout >120.0s
FAILED integration/backend_test.py::test_wasm_collatz[Language.QIR-H1-1E] - pytket.extensions.quantinuum.backends.quantinuum.GetResultFailed: Cannot retrieve result; job status is Circui...
FAILED integration/backend_test.py::test_wasm_state[Language.QASM-H1-1E] - Failed: Timeout >120.0s
FAILED integration/backend_test.py::test_wasm_state[Language.QIR-H1-1E] - pytket.extensions.quantinuum.backends.quantinuum.GetResultFailed: Cannot retrieve result; job status is Circui...
FAILED integration/backend_test.py::test_wasm_multivalue[Language.QASM-H1-1E] - Failed: Timeout >120.0s
FAILED integration/backend_test.py::test_wasm_multivalue[Language.QIR-H1-1E] - ValueError: wasm function which return more than one value are not supported yet
```

which are all in WASM tests except for the `assert 2 > 2` failure in `test_simulator` (from the line `assert len(noisy_counts) > 2`) which may indicate that noisy simulation is not working with QIR submissions.

I still suggest that we merge this and treat the above as bugs to be fixed, since it seems QIR submission is working better than it was before?

**Review by cqc-melf — APPROVED** [review]

**Pull request merged**
