### PR TITLE
Remove `no_opt` and `allow_2q_gate_rebase` options

### PR DESCRIPTION
**Pull request by cqc-alec**
# Description

Set both `no-opt` and `noreduce` to `True` to prevent any changes to the submitted circuit. It is assumed that the submitted circuit is what is desired to be run.

(It's still possible for these options to be overridden by providing an `options` dictionary to `process_circuits()` or `submit_program()`, but this is very much opt-in for those who know what they're doing.)

# Checklist

- [x] I have performed a self-review of my code.
- [ ] I have commented hard-to-understand parts of my code.
- [x] I have made corresponding changes to the public API documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have updated the changelog with any user-facing changes.

### CODE REVIEW

**Comment by cqc-alec** [comment]
There is a timeout on one of the tests, which I think we just have to ignore.

**Comment by irfankhan10** [comment]
Hi Alec, this looks good. Is it worth setting the L4 option nativetq, or is that not needed?

**Comment by cqc-alec** [comment]
> Hi Alec, this looks good. Is it worth setting the L4 option nativetq, or is that not needed?

Since we set `noreduce` to `True` by default I don't think it's needed. In the (presumably rare) case where the user wants `noreduce=False` but still wants to specify `nativetq`, they can still do so via the `options` argument.

**Comment by irfankhan10** [comment]
Thanks Alec. 

Just want to clarify: 
- **no-opt**=True, means **tket-op-level** does not need to be specified?
- **no-reduce**=True means **nativetq** does not need to be specified?

**Comment by cqc-alec** [comment]
> Just want to clarify:
> 
>     * **no-opt**=True, means **tket-op-level** does not need to be specified?
> 
>     * **no-reduce**=True means **nativetq** does not need to be specified?

That's my understanding yes.

**Review by irfankhan10 — APPROVED** [review]

**Pull request merged**
